services:
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - apps/orders/.env
    depends_on:
      - billing
      - auth
      - items
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  billing:
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: npm run start:dev billing
    env_file:
      - apps/billing/.env
    depends_on:
      - auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mail:
    build:
      context: .
      dockerfile: ./apps/mail/Dockerfile
      target: development
    command: npm run start:dev mail
    env_file:
      - apps/mail/.env
    depends_on:
      - auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  items:
    build:
      context: .
      dockerfile: ./apps/items/Dockerfile
      target: development
    command: npm run start:dev items
    env_file:
      - apps/items/.env
    depends_on:
      - auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3002:3002'

  profile:
    build:
      context: .
      dockerfile: ./apps/profile/Dockerfile
      target: development
    command: npm run start:dev profile
    env_file:
      - apps/profile/.env
    depends_on:
      - auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3004:3004'

  job:
    build:
      context: .
      dockerfile: ./apps/job/Dockerfile
      target: development
    command: npm run start:dev job
    env_file:
      - apps/job/.env
    depends_on:
      - auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3005:3005'

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

volumes:
  mongodb_master_data:
    driver: local
